# This is the basic pipeline use for the project
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml
#workflow:
#  rules:
#    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'

variables:
  DOCKERNAME: docker.signintra.com/qa-dashboard/qa-dashboard/flightctrl/sqdashboard:latest

default:
  image: $DOCKERNAME

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - predeploy
  - deploy
  - testrail
  - etl


include:
    - component: $CI_SERVER_FQDN/tap/cicd-components/docker/build@~latest
      inputs:
        stage: build
#  when: manual

sqdashboard-job-unit-test:
  image: ${CI_REGISTRY_IMAGE}:sha-${CI_COMMIT_SHORT_SHA}
  stage: test
  environment: production
  script:
    - echo "Start of the Unit Tests"
    - envsubst < ${CI_PROJECT_DIR}/FC_Test_tmpl.json > ${CI_PROJECT_DIR}/FC_Test.json
    - python3 -m pytest

sqdashboard-job-prework:      # This job runs in the deploy stage.
  stage: predeploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  only:
    refs:
      - main
  script:
    - echo "Run is starting"
    - envsubst < ${CI_PROJECT_DIR}/FC_Test_tmpl.json > ${CI_PROJECT_DIR}/FC_Test.json
    - export PYTHONPATH=${CI_PROJECT_DIR}
    #- python3 ${CI_PROJECT_DIR}/testMSSQL.py
    #- the jira_gilds parameter represents the target jira instance. it can be also jira_issues.
    - python3 ${CI_PROJECT_DIR}/src/init/InitLoadSetup.py FC_Test fc_db jira_tsc
  artifacts:
    paths:
      - refreshIDX.txt

sqdashboard-job-TestRail TSC:      # This job runs in the deploy stage.
  stage: testrail  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  dependencies:
    - sqdashboard-job-prework
  only:
    refs:
      - main
  script:
    - echo "Run is starting"
    - envsubst < ${CI_PROJECT_DIR}/FC_Test_tmpl.json > ${CI_PROJECT_DIR}/FC_Test.json
    - export PYTHONPATH=${CI_PROJECT_DIR}
    #- python3 ${CI_PROJECT_DIR}/testMSSQL.py
    #- the jira_gilds parameter represents the target jira instance. it can be also jira_issues.
    - cat refreshIDX.txt
    - python3 ${CI_PROJECT_DIR}/src/init/Connect2TestRail.py FC_Test fc_db jira_tsc

sqdashboard-job-TestRail TSC1:      # This job runs in the deploy stage.
  stage: testrail  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  dependencies:
    - sqdashboard-job-prework
  only:
    refs:
      - main
  script:
    - echo "Run is starting"
    - envsubst < ${CI_PROJECT_DIR}/FC_Test_tmpl.json > ${CI_PROJECT_DIR}/FC_Test.json
    - export PYTHONPATH=${CI_PROJECT_DIR}
    #- python3 ${CI_PROJECT_DIR}/testMSSQL.py
    #- the jira_gilds parameter represents the target jira instance. it can be also jira_issues.
    - cat refreshIDX.txt
    - python3 ${CI_PROJECT_DIR}/src/init/Connect2TestRail.py FC_Test fc_db jira_tsc1

sqdashboard-job-TestRail GILDS:      # This job runs in the deploy stage.
  stage: testrail  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  dependencies:
    - sqdashboard-job-prework
  only:
    refs:
      - testrail
  script:
    - echo "Run is starting"
    - envsubst < ${CI_PROJECT_DIR}/FC_Test_tmpl.json > ${CI_PROJECT_DIR}/FC_Test.json
    - export PYTHONPATH=${CI_PROJECT_DIR}
    #- python3 ${CI_PROJECT_DIR}/testMSSQL.py
    #- the jira_gilds parameter represents the target jira instance. it can be also jira_issues.
    - cat refreshIDX.txt
    - python3 ${CI_PROJECT_DIR}/src/init/Connect2TestRail.py FC_Test fc_db jira_gilds

sqdashboard-job-jira_tsc:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  dependencies:
    - sqdashboard-job-prework
  only:
    refs:
      - main
  script:
    - echo "Run is starting"
    - envsubst < ${CI_PROJECT_DIR}/FC_Test_tmpl.json > ${CI_PROJECT_DIR}/FC_Test.json
    - export PYTHONPATH=${CI_PROJECT_DIR}
    #- python3 ${CI_PROJECT_DIR}/testMSSQL.py
    #- the jira_gilds parameter represents the target jira instance. it can be also jira_issues.
    - cat refreshIDX.txt
    - python3 ${CI_PROJECT_DIR}/src/init/Connect2Sqlserver.py FC_Test fc_db jira_tsc

sqdashboard-job-jira_tsc1:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  dependencies:
    - sqdashboard-job-prework
  only:
    refs:
      - main
  script:
    - echo "Run is starting"
    - envsubst < ${CI_PROJECT_DIR}/FC_Test_tmpl.json > ${CI_PROJECT_DIR}/FC_Test.json
    - export PYTHONPATH=${CI_PROJECT_DIR}
    #- python3 ${CI_PROJECT_DIR}/testMSSQL.py
    #- the jira_gilds parameter represents the target jira instance. it can be also jira_issues.
    - cat refreshIDX.txt
    - python3 ${CI_PROJECT_DIR}/src/init/Connect2Sqlserver.py FC_Test fc_db jira_tsc1

sqdashboard-job-jira_gilds:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  dependencies:
    - sqdashboard-job-prework
  script:
    - echo "Run is starting"
    - envsubst < ${CI_PROJECT_DIR}/FC_Test_tmpl.json > ${CI_PROJECT_DIR}/FC_Test.json
    - export PYTHONPATH=${CI_PROJECT_DIR}
    #- python3 ${CI_PROJECT_DIR}/testMSSQL.py
    #- the jira_gilds parameter represents the target jira instance. it can be also jira_issues.
    - python3 ${CI_PROJECT_DIR}/src/init/Connect2Sqlserver.py FC_Test fc_db jira_gilds

sqdashboard-job-etl:      # This job runs in the deploy stage.
  stage: etl  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  dependencies: 
    - sqdashboard-job-jira_gilds
  script:
    - echo "Run is starting"
    - envsubst < ${CI_PROJECT_DIR}/FC_Test_tmpl.json > ${CI_PROJECT_DIR}/FC_Test.json
    - export PYTHONPATH=${CI_PROJECT_DIR}
    - python3 ${CI_PROJECT_DIR}/etl/bugStatistics/releaseQualityMatrix.py FC_Test fc_db
