sq.fact_ji_squads
sq.fact_ji_fixversions
sq.fact_ji_labels
sq.fact_ji_components
sq.fact_ji_versions
sq.dim_ji_releases
sq.fact_ji_issues
sq.fact_tr_tests
sq.fact_tr_runs
sq.fact_tr_users
sq.fact_tr_groups
sq.fact_tr_case_fields
sq.fact_tr_refs
sq.dim_tr_cases
sq.dim_tr_case_types
sq.fact_tr_section
sq.fact_tr_suites
sq.dim_tr_projects
sq.etl_bugs_agg
sq.etl_bugs_stats
sq.dim_sq_config